name: ns

default-extensions:
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - DerivingStrategies
  - FlexibleInstances
  - BlockArguments
  - NoImplicitPrelude
  - LambdaCase
  - DeriveDataTypeable

dependencies:
  - base >= 4.14.1.0 && < 5
  - text

executables:
  ns-exe:
    main: Main.hs
    source-dirs: app
    ghc-options: [-Wincomplete-patterns]
    dependencies:
      - ns
      - filepath

library:
  source-dirs: src
  dependencies:
    - megaparsec
    - mtl
    - uniplate
