name: ns

default-extensions:
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - DerivingStrategies
  - FlexibleInstances
  - BlockArguments
  - NoImplicitPrelude
  - LambdaCase

dependencies:
  - base >= 4.14.1.0 && < 5
  - text

ghc-options:
  - -Wincomplete-patterns

executables:
  ns-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - ns
      - filepath

library:
  source-dirs: src

  dependencies:
    - megaparsec
    - mtl
    - containers
